### ISSUE TITLE
docker compose in vs2019 creates error

### ISSUE THREAD

**Issue by punkouter2018** [OpenCodeFoundation/eSchool#95]
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at OpenCodeFoundation.eSchool.Identity.API.Program.Main(String[] args) in C:\Users\punko\Source\Repos\eSchool\src\Services\Identity\Identity.API\Program.cs:line 12

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: IdentityServer4.Validation.ScopeValidator Lifetime: Transient ImplementationType: IdentityServer4.Validation.ScopeValidator': Unable to resolve service for type 'IdentityServer4.Stores.IResourceStore' while attempting to activate 'IdentityServer4.Validation.ScopeValidator'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'IdentityServer4.Stores.IResourceStore' while attempting to activate 'IdentityServer4.Validation.ScopeValidator'.

**Comment by punkouter2018** [comment]
working if I use command line though.. perhaps identity is not working and the vs2019 debugger is catching it

**Comment by ratanparai** [comment]
I have removed the service as it was in incomplete state.
